# Site settings
title: web application developer | allanchangcl
name: Allan Chang
email: allan@clchang.net
description: > # this means to ignore newlines until "baseurl:"
 Personal Blog on web application development. Notes on learn to 
 code in ruby on rails, erlang and anything else related to html code,
 css, cloud computing and webservers

# the subpath of your site, e.g. /blog/
baseurl: "http://clchangnet.github.io"

# the base hostname & protocol for your site
url: "/"
# url: "http://clchang.net"

# Social
mobile: "tel:+60122956066"
twitter: "https://twitter.com/clchangnet"
facebook: "https://www.facebook.com/clchangnet"
google_plus: "http://plus.google.com/118387636159308776887"
github: ""

# Scripts
google_analytics: # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: clchangnet

# Localization strings
str_continue_reading: "Continue reading"
str_next: "Next"
str_prev: "Prev"

# PAGINATION
paginate: 5
paginate_path: "page:num"
post_navigation: true

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments

# prevent inserting ids into tags
kramdown:
  auto_ids: false